pre-commit.ci:
  autofix_commit_msg: |
    chore [pre-commit.ci] commit: auto fixes from pre-commit.ci hooks
  autoupdate_commit_msg: |
    chore [pre-commit.ci] pre-commit autoupdate
  autofix_prs: true
  autoupdate_branch: epic-kore
  autoupdate_schedule: monthly
  push:
    branches:
      - epic-kore
  skip:
    - editorconfig-checker
    - trailing-whitespace
    - end-of-file-fixer
    - mixed-line-ending
    - check-yaml
  submodules: false
fail_fast: false
default_language_version:
  python: python3.11
repos:
  - repo: local
    hooks:
      - id: add-pre-commit-config
        name: Add pre-commit config
        entry: git add .pre-commit-config.yaml
        language: system
        pass_filenames: false
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^staticfiles/admin/|^docs/
      - id: check-yaml
        exclude: ^pep8speaks\.yml$
      - id: end-of-file-fixer
        exclude: ^staticfiles/|^docs/
      - id: double-quote-string-fixer
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [ --check]
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.10  # or any later Vulture version
    hooks:
      - id: vulture
        args: [--min-confidence, '80']
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports # archived, depreacted
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        # automatically formats docstrings: follows a subset of PEP 257
        additional_dependencies: [ tomli ]
        args: [ --in-place, --config, ./pyproject.toml ]
  - repo: https://github.com/asottile/dead
    rev: v1.5.2
    hooks:
      - id: dead
        exclude: ^dash_and_do/settings.py|^docs/
#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.0.3
#    hooks:
#      - id: detect-secrets
#        args: ['--baseline', 'secrets.baseline']
#        exclude: 'secrets.baseline'
#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.5
#    hooks:
#      - id: bandit
#        args: ["-r", "-lll"]
#        exclude: *fixtures
