repos:
  # Pre-Commit-Hooks
  - repo : https://github.com/pre-commit/pre-commit-hooks
    rev  : v4.4.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
      - id: check-yaml
      - id: end-of-file-fixer
  # EditorConfig
  - repo : https://github.com/editorconfig-checker/editorconfig-checker.python
    rev  : '2.7.1'  # pick a git hash / tag to point to
    hooks:
      - id   : editorconfig-checker
        alias: ec
  # Prettier
  - repo : https://github.com/pre-commit/mirrors-prettier
    rev  : v3.0.0 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  ############ PYTHON ############
  # Ruff (at end, with auto-fix)
  - repo : https://github.com/astral-sh/ruff-pre-commit
    rev  : v0.0.277
    hooks:
      - id  : ruff
        args: [ --fix, --exit-non-zero-on-fix ]